### PR TITLE
Add 4 new functions

### PR DESCRIPTION
**Pull request by bruh-9000**
increase and decrease entity and player attributes by a number

### CODE REVIEW

**Review by sloont — COMMENTED** [review]
Are these really necessary? It's easy enough to just use `setEntityAttribute` etc. right?

**Comment by bruh-9000** [comment]
Yeah idk I just got requests from the community and people like sonadam were requesting stuff like this, I forgot who else

**Comment by Grenagar** [comment]
> Are these really necessary? It's easy enough to just use `setEntityAttribute` etc. right?

maybe its not necessary, but we have similar actions for variables, so why not have for attributes, what you think? 
image

**Comment by bruh-9000** [comment]
I also could maybe do this for entity attributes I just didn't already since they aren't only numbers so more work lol

**Comment by minotalen** [comment]
> Are these really necessary? It's easy enough to just use `setEntityAttribute` etc. right?

Yeah we should make these easier for beginners. It's quite annoying to use the set entity attribute, then add a calc, then add the entity attribute again to first param. Also makes the code more difficult to read & understand. Pretty sure I remember @m0dE wondering why this is not a feature in a call some time ago.

Imo this is missing entity and player vars as well, but would be ok with omitting those for now since vars are often not just numbers.

**Comment by Grenagar** [comment]
> > Are these really necessary? It's easy enough to just use `setEntityAttribute` etc. right?
> 
> Yeah we should make these easier for beginners. It's quite annoying to use the set entity attribute, then add a calc, then add the entity attribute again to first param. Also makes the code more difficult to read & understand. Pretty sure I remember @m0dE wondering why this is not a feature in a call some time ago.
> 
> Imo this is missing entity and player vars as well, but would be ok with omitting those for now since vars are often not just numbers.

I think lets add for all at once - player and entity attribute and variables

**Comment by bruh-9000** [comment]
I can look into adding for variables soon

**Comment by PineappleBrain** [comment]
this good, can make beautiful code that no need to write things two time

**Comment by m0dE** [comment]
I'm on the fence about this

**Comment by m0dE** [comment]
I'll close for now. happy to re-open later

**Pull request closed without merging**
