### PR TITLE
Fixed item display when changing items between inventory slots

### PR DESCRIPTION
**Pull request by LL-10**
The few lines of code I deleted where mistakenly showing any item when moved inside the inventory, and hiding any item when moved to backpack.

### CODE REVIEW

**Comment by nagendraallam** [comment]
This bug occurs only on 2D phaser renderer

**Comment by LL-10** [comment]
I updated my pull request with a new commit: it cleans the code by moving the item state changes to a method, and adds a check for items in backpack, that replaces the code that I removed with the first commit, removing the bugs caused by that code. This default behaviour of items to get hidden when in backpack can be overridden by setting a 'backpacked' state.

Here is the game sample I made for testing:
[Bug testing_2024526_107.json](https://github.com/moddio/moddio2/files/15447098/Bug.testing_2024526_107.json)

**Comment by sloont** [comment]
there is already a method on `TaroEntity` for updating state. Methods like Item's `changeSlotIndex` have no business setting state.

I have found an issue with items displaying when they shouldn't that is in a way related to this code, but the solution shouldn't be trying to refactor/add a[nother] `setState` method when the issue does not come from `setState` itself.

I am currently working on finding a solution for Items incorrectly being shown when dragged between inventory slots.

**Comment by LL-10** [comment]
Dear Mr. Sloont, your answer shows how you don’t even know what setState method is for! My refactor is not at all making another setState method, but instead avoid repeating the same checks and calls multiple times and facilitate debug. In fact my solution is perfect, as it is very clean and leaves no space to mistake/bug.
If you closed because you are offended that I corrected your leaky code, then consider leaving this issue to somebody else in the staff, and reopen the pull request.

**Comment by LL-10** [comment]
> Methods like Item's `changeSlotIndex` have no business setting state.

As you don't know, I'll teach you: the display of an item depends on its body type: if unset (none), the item will be hidden, else it will display as the user set in the body type. The right body type (together with animation, etc) is assigned by setting the entity state and not just by calling the show() method. And forcing hide with hide() method is a disaster too. This is why your code didn't work as expected and mine does, and that is also why you are losing your time looking for a solution in your old path.
To prove this, just test and see how the items showing when they should be hidden, also have no anchor set and appear centered on the unit. This happens because you did not set the state, but forced showing/hiding instead.

**Pull request closed without merging**
