### PR TITLE
Fix allUnitsOfUnitType

### PR DESCRIPTION
**Pull request by bruh-9000**
text.type was the original value of type but it should've been text.unitType

### CODE REVIEW

**Comment by bruh-9000** [comment]
fixes https://github.com/moddio/moddio2/issues/668

**Comment by minotalen** [comment]
so this script works
grafik
When does the action break?

**Comment by bruh-9000** [comment]
I don't know, when I made this it was broken. Maybe it was patched in the time between since nobody merged the PR...

**Review by minotalen — APPROVED** [review]
Great catch, thanks a bunch!

**Comment by sloont** [comment]
looks like this was a new feature that i implemented here: #[d3fb144](https://github.com/moddio/moddio2/commit/d3fb1442726ea421d3ceeff39725181f7a5b59cb)

looking at the blame, these changes were rolled back due to another issue (commit [8b3fbcf](https://github.com/moddio/moddio2/commit/8b3fbcf301821ef2d2821e388bb0f9704562fae5))

i think m0de and i were fixing these and they were added as a part of a larger group of changes, and the revert captured the right changes.

additionally, this is made more complex by the fact that VariableComponent.js was renamed to ParameterComponent.js and VariableComponent.js is now used as the name of a different file entirely.

ParameterComponent.js shows that these issues no longer exist on master branch, so i will close this PR.

**Comment by sloont** [comment]
looks like this was a new feature that i implemented here: [d3fb144](https://github.com/moddio/moddio2/commit/d3fb1442726ea421d3ceeff39725181f7a5b59cb)

looking at the blame, these changes were rolled back due to another issue (commit [8b3fbcf](https://github.com/moddio/moddio2/commit/8b3fbcf301821ef2d2821e388bb0f9704562fae5))

i think m0de and i were fixing these and they were added as a part of a larger group of changes, and the revert captured the right changes.

additionally, this is made more complex by the fact that `VariableComponent.js` was renamed to `ParameterComponent.js` and `VariableComponent.js` is now used as the name of a different file entirely.

`ParameterComponent.js` shows that these issues no longer exist on master branch, so i will close this PR.

**Comment by sloont** [comment]
@bruh-9000

**Pull request closed without merging**
