### PR TITLE
Add new trigger, playerGetsNewHighscore

### PR DESCRIPTION
**Pull request by bruh-9000**

### CODE REVIEW

**Review by sloont — COMMENTED** [review]
this seems ok, but i think there will be some confusion down the road. this trigger will only fire on server because this function is only ever called on the server

**Comment by bruh-9000** [comment]
So that means that it won't work on CSP?

**Comment by Grenagar** [comment]
it will work on global and entity scripts, but only if action run on server, client will not know about this trigger

**Comment by bruh-9000** [comment]
So that means that it won't work on CSP?

**Review by Grenagar — APPROVED** [review]

**Pull request merged**
