### PR TITLE
Fix filter

### PR DESCRIPTION
**Pull request by bruh-9000**
This adds a filter for changing unit names, player names, and floating text.

### CODE REVIEW

**Comment by bruh-9000** [comment]
Draft as this needs to be tested since the chat component thing isn't available for me

**Comment by bruh-9000** [comment]
Filters unit names, player names, shops and floating text

**Comment by VietnamNeko** [comment]
I think this is not ideal, as the filter is very sensitive with certain words (like god).

**Comment by bruh-9000** [comment]
@VietnamNeko I don't think that is something that would be worthy of not adding a filter for these things, this should be an issue for the filter for everything.

**Review by Grenagar — APPROVED** [review]

**Comment by VietnamNeko** [comment]
I still disagree with this pr, the filter should be only used on player inputs

**Comment by bruh-9000** [comment]
Closing and making new PR due to conflict

**Pull request closed without merging**
